# Generated by Django 4.1.7 on 2023-03-27 01:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('ClienteTelefono', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only numbers are allowed.')])),
                ('ClienteCorreo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpleadoNombre', models.CharField(max_length=50)),
                ('EmpleadoEdad', models.SmallIntegerField()),
                ('EmpleadoTel', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only numbers are allowed.')])),
                ('EmpleadoSalario', models.IntegerField()),
                ('EmpleadoCorreo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idProveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=50)),
                ('ProveedorDireccion', models.CharField(max_length=100)),
                ('ProveedorTelefono', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only numbers are allowed.')])),
                ('ProveedorCorreo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('ProductoDescripcion', models.CharField(max_length=100)),
                ('ProductoPrecio', models.IntegerField()),
                ('Inventario', models.IntegerField()),
                ('idProovedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadito.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('Subtotal', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('MetodoPago', models.CharField(max_length=20)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadito.empleados')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadito.producto')),
                ('nombreCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadito.cliente')),
            ],
        ),
    ]
