# Generated by Django 4.1.7 on 2023-03-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpleadoNombre', models.CharField(max_length=50)),
                ('EmpleadoEdad', models.SmallIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idProveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadito.cliente')),
            ],
        ),
    ]
