# Generated by Django 4.1.7 on 2023-03-27 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0002_rename_idproovedor_producto_idproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadito.proveedores'),
        ),
    ]
